### ISSUE TITLE
No Audio Coming Out of Pi

### ISSUE THREAD

**Issue by ahmadnazirafiq** [hdmvide/Homebridge-SwitchSound#4]
It used to work before until I had to rebuild Homebridge from scratch and restored backup from previous instance. No error messages in Homebridge log:

> [23/02/2021, 23:12:21] [SwitchSound] Playing Sound.... /home/pi/Sounds/nuclearalarm.mp3
[23/02/2021, 23:12:23] [SwitchSound] Playing Sound.... /home/pi/Sounds/nuclearalarm.mp3
[23/02/2021, 23:12:24] [SwitchSound] Playing Sound.... /home/pi/Sounds/nuclearalarm.mp3
[23/02/2021, 23:12:26] [SwitchSound] Playing Sound.... /home/pi/Sounds/nuclearalarm.mp3
[23/02/2021, 23:12:27] [SwitchSound] Playing Sound.... /home/pi/Sounds/nuclearalarm.mp3

Here's my config:

> {
    "platform": "SwitchSound",
    "name": "SwitchSound",
    "debug": false,
    "defaultSoundPlayer": "/usr/bin/omxplayer.bin",
    "accessories": [
        {
            "accessory": "SwitchSound",
            "id": "000000000001",
            "name": "Alarm Sound",
            "soundFile": "/home/pi/Sounds/nuclearalarm.mp3",
            "soundOptions": [],
            "loop": false,
            "volume": 100,
            "debug": false,
            "sequence": false
        }
    ]
}

OMX Player was already installed. I also have an AirPlay server running on the Pi with external speaker connected via its 3.5 jack and it outputs audio just fine. Just not your plugin. Tried uninstalling and reconfiguring, but nothing works. Any ideas?

**Comment by hdmvide** [comment]
Hi,
have you tried to run omxplayer from the terminal?
Usually when no sounds are played from HomeBridge, it is because the HomeBridge user does not have privileges.

have you assigned permissions to your user?

try

sudo passwd INSERT_YOUR_USERNAME_HOMEBRIDGE
sudo usermod -a -G video INSERT_YOUR_USERNAME_HOMEBRIDGE

**Comment by ahmadnazirafiq** [comment]
Hi,

I've tried sudo passwd pi and sudo usermod -a -G video pi and reboot Raspberry. The switch in HomeKit immediately turns off when toggled on. Still no sound too.

How do I run omxplayer from Terminal?

**Comment by hdmvide** [comment]
> Hi,
> 
> I've tried sudo passwd pi and sudo usermod -a -G video pi and reboot Raspberry. The switch in HomeKit immediately turns off when toggled on. Still no sound too.
> 
> How do I run omxplayer from Terminal?

are you sure pi is the homebridge user?  it is usually not used anymore, especially if you are using packaged distributions.  To verify the HomeBridge user, you need to find the service file: 

homebridge.service

usually the path is this:

/etc/systemd/system/homebridge.service

try to edit it from the terminal with this command:

sudo nano /etc/systemd/system/homebridge.service


inside this file you have to look for the User variable.  the user assigned to the variable is the one to whom you must give permissions.

**Comment by ahmadnazirafiq** [comment]
This is what I'm seeing though in Homebridge.service:

[Unit]
Description=Homebridge
Wants=network-online.target
After=syslog.target network-online.target

[Service]
Type=simple
User=pi
PermissionsStartOnly=true
WorkingDirectory=/var/lib/homebridge
EnvironmentFile=/etc/default/homebridge
ExecStartPre=-run-parts /etc/hb-service/homebridge/prestart.d
ExecStartPre=-/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js before$
ExecStart=/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js run $HOMEB$
Restart=always
RestartSec=3
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID C$
AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target

**Comment by hdmvide** [comment]
> This is what I'm seeing though in Homebridge.service:
> 
> [Unit]
> Description=Homebridge
> Wants=network-online.target
> After=syslog.target network-online.target
> 
> [Service]
> Type=simple
> User=pi
> PermissionsStartOnly=true
> WorkingDirectory=/var/lib/homebridge
> EnvironmentFile=/etc/default/homebridge
> ExecStartPre=-run-parts /etc/hb-service/homebridge/prestart.d
> ExecStartPre=-/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js before$
> ExecStart=/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js run $HOMEB$
> Restart=always
> RestartSec=3
> KillMode=process
> CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID C$
> AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE
> 
> [Install]
> WantedBy=multi-user.target

try to execute this command from the terminal:

omxplayer PATH_SOUND_FILE

this way you can check if the music playback works

**Comment by ahmadnazirafiq** [comment]
OMG It works!

Thank you for helping this out. I appreciate your time!

**Comment by hdmvide** [comment]
> OMG It works!
> 
> Thank you for helping this out. I appreciate your time!

So, does it work execute by HomeKit?

**Comment by ahmadnazirafiq** [comment]
Yes it does!

**Comment by hdmvide** [comment]
> Yes it does!

great!  it was a pleasure
